version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: crudapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crudapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crudapp-backend
    environment:
      SPRING_PROFILE: docker
      # These are used by application-docker.properties when not overridden
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: crudapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      APP_FRONTEND_URL: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_AUTH_PROVIDER: form
    container_name: crudapp-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  adminer:
    image: adminer:4
    container_name: crudapp-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
    driver: local
